import tensorflow as tf


kuairand_defaults = 60 * [tf.constant(100, dtype=tf.int32)] \
    + [
    tf.constant(2, dtype=tf.int32),
    tf.constant(7, dtype=tf.int32),
    tf.constant(50, dtype=tf.int32),
    tf.constant(1471, dtype=tf.int32),
    tf.constant(15, dtype=tf.int32),
    tf.constant(34, dtype=tf.int32),
    tf.constant(3, dtype=tf.int32),
    tf.constant(118, dtype=tf.int32),
    tf.constant(454, dtype=tf.int32),
    tf.constant(7, dtype=tf.int32),
    tf.constant(5, dtype=tf.int32),
    tf.constant(5, dtype=tf.int32),
]  \
    + [tf.constant(2, dtype=tf.int32)] * 6  \
    + [
    tf.constant(9, dtype=tf.int32),
    tf.constant(8, dtype=tf.int32),
    tf.constant(9, dtype=tf.int32),
    tf.constant(7, dtype=tf.int32),
    tf.constant(8, dtype=tf.int32),
    tf.constant(3, dtype=tf.int32),
    tf.constant(14, dtype=tf.int32),
    tf.constant(58, dtype=tf.int32),
    tf.constant(2, dtype=tf.int32),
    tf.constant(27077, dtype=tf.int32),
    tf.constant(7551, dtype=tf.int32),
    tf.constant(6489, dtype=tf.int32),
    tf.constant(7172, dtype=tf.int32),
    tf.constant(2, dtype=tf.int32),
    tf.constant(12, dtype=tf.int32),
    tf.float32,
    tf.float32
]

feature_config = [
    {"feature_name": "id_video_duration", "is_ragged": False,
        "row": 0, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_server_width", "is_ragged": False,
        "row": 1, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_server_height", "is_ragged": False,
        "row": 2, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_show_cnt", "is_ragged": False,
        "row": 3, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_show_user_num", "is_ragged": False,
        "row": 4, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_play_cnt", "is_ragged": False,
        "row": 5, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_play_user_num", "is_ragged": False,
        "row": 6, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_play_duration", "is_ragged": False,
        "row": 7, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_complete_play_cnt", "is_ragged": False,
        "row": 8, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_complete_play_user_num", "is_ragged": False,
        "row": 9, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_valid_play_cnt", "is_ragged": False,
        "row": 10, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_valid_play_user_num", "is_ragged": False,
        "row": 11, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_long_time_play_cnt", "is_ragged": False,
        "row": 12, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_long_time_play_user_num", "is_ragged": False,
        "row": 13, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_short_time_play_cnt", "is_ragged": False,
        "row": 14, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_short_time_play_user_num", "is_ragged": False,
        "row": 15, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_play_progress", "is_ragged": False,
        "row": 16, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_comment_stay_duration", "is_ragged": False,
        "row": 17, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_like_cnt", "is_ragged": False,
        "row": 18, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_like_user_num", "is_ragged": False,
        "row": 19, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_click_like_cnt", "is_ragged": False,
        "row": 20, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_double_click_cnt", "is_ragged": False,
        "row": 21, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_cancel_like_cnt", "is_ragged": False,
        "row": 22, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_cancel_like_user_num", "is_ragged": False,
        "row": 23, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_comment_cnt", "is_ragged": False,
        "row": 24, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_comment_user_num", "is_ragged": False,
        "row": 25, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_direct_comment_cnt", "is_ragged": False,
        "row": 26, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_reply_comment_cnt", "is_ragged": False,
        "row": 27, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_delete_comment_cnt", "is_ragged": False,
        "row": 28, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_delete_comment_user_num", "is_ragged": False,
        "row": 29, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_comment_like_cnt", "is_ragged": False,
        "row": 30, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_comment_like_user_num", "is_ragged": False,
        "row": 31, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_follow_cnt", "is_ragged": False,
        "row": 32, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_video_follow_user_num", "is_ragged": False,
        "row": 33, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_cancel_follow_cnt", "is_ragged": False,
        "row": 34, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_cancel_follow_user_num", "is_ragged": False,
        "row": 35, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_share_cnt", "is_ragged": False,
        "row": 36, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_share_user_num", "is_ragged": False,
        "row": 37, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_download_cnt", "is_ragged": False,
        "row": 38, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_download_user_num", "is_ragged": False,
        "row": 39, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_report_cnt", "is_ragged": False,
        "row": 40, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_report_user_num", "is_ragged": False,
        "row": 41, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_reduce_similar_cnt", "is_ragged": False,
        "row": 42, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_reduce_similar_user_num", "is_ragged": False,
        "row": 43, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_collect_cnt", "is_ragged": False,
        "row": 44, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_collect_user_num", "is_ragged": False,
        "row": 45, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_cancel_collect_cnt", "is_ragged": False,
        "row": 46, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_cancel_collect_user_num", "is_ragged": False,
        "row": 47, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_direct_comment_user_num", "is_ragged": False,
        "row": 48, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_reply_comment_user_num", "is_ragged": False,
        "row": 49, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_share_all_cnt", "is_ragged": False,
        "row": 50, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_share_all_user_num", "is_ragged": False,
        "row": 51, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_outsite_share_all_cnt", "is_ragged": False,
        "row": 52, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_follow_user_num", "is_ragged": False,
        "row": 53, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_fans_user_num", "is_ragged": False,
        "row": 54, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_friend_user_num", "is_ragged": False,
        "row": 55, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_register_days", "is_ragged": False,
        "row": 56, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_counts", "is_ragged": False,
        "row": 57, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_profile_stay_time", "is_ragged": False,
        "row": 58, "hash_size": 101, "type": "unknown"},
    {"feature_name": "id_comment_stay_time", "is_ragged": False,
        "row": 59, "hash_size": 101, "type": "unknown"},
    {"feature_name": "onehot_feat0", "is_ragged": False,
        "row": 60, "hash_size": 3, "type": "unknown"},
    {"feature_name": "onehot_feat1", "is_ragged": False,
        "row": 61, "hash_size": 8, "type": "unknown"},
    {"feature_name": "onehot_feat2", "is_ragged": False,
        "row": 62, "hash_size": 51, "type": "unknown"},
    {"feature_name": "onehot_feat3", "is_ragged": False,
        "row": 63, "hash_size": 1472, "type": "unknown"},
    {"feature_name": "onehot_feat4", "is_ragged": False,
        "row": 64, "hash_size": 16, "type": "unknown"},
    {"feature_name": "onehot_feat5", "is_ragged": False,
        "row": 65, "hash_size": 35, "type": "unknown"},
    {"feature_name": "onehot_feat6", "is_ragged": False,
        "row": 66, "hash_size": 4, "type": "unknown"},
    {"feature_name": "onehot_feat7", "is_ragged": False,
        "row": 67, "hash_size": 119, "type": "unknown"},
    {"feature_name": "onehot_feat8", "is_ragged": False,
        "row": 68, "hash_size": 455, "type": "unknown"},
    {"feature_name": "onehot_feat9", "is_ragged": False,
        "row": 69, "hash_size": 8, "type": "unknown"},
    {"feature_name": "onehot_feat10", "is_ragged": False,
        "row": 70, "hash_size": 6, "type": "unknown"},
    {"feature_name": "onehot_feat11", "is_ragged": False,
        "row": 71, "hash_size": 6, "type": "unknown"},
    {"feature_name": "onehot_feat12", "is_ragged": False,
        "row": 72, "hash_size": 3, "type": "unknown"},
    {"feature_name": "onehot_feat13", "is_ragged": False,
        "row": 73, "hash_size": 3, "type": "unknown"},
    {"feature_name": "onehot_feat14", "is_ragged": False,
        "row": 74, "hash_size": 3, "type": "unknown"},
    {"feature_name": "onehot_feat15", "is_ragged": False,
        "row": 75, "hash_size": 3, "type": "unknown"},
    {"feature_name": "onehot_feat16", "is_ragged": False,
        "row": 76, "hash_size": 3, "type": "unknown"},
    {"feature_name": "onehot_feat17", "is_ragged": False,
        "row": 77, "hash_size": 3, "type": "unknown"},
    {"feature_name": "index_user_active_degree", "is_ragged": False,
        "row": 78, "hash_size": 10, "type": "unknown"},
    {"feature_name": "index_user_follow_user_num_range",
        "is_ragged": False, "row": 79, "hash_size": 9, "type": "unknown"},
    {"feature_name": "index_fans_user_num_range", "is_ragged": False,
        "row": 80, "hash_size": 10, "type": "unknown"},
    {"feature_name": "index_friend_user_num_range", "is_ragged": False,
        "row": 81, "hash_size": 8, "type": "unknown"},
    {"feature_name": "index_register_days_range", "is_ragged": False,
        "row": 82, "hash_size": 9, "type": "unknown"},
    {"feature_name": "index_video_type", "is_ragged": False,
        "row": 83, "hash_size": 4, "type": "unknown"},
    {"feature_name": "index_upload_type", "is_ragged": False,
        "row": 84, "hash_size": 15, "type": "unknown"},
    {"feature_name": "index_tag", "is_ragged": False,
        "row": 85, "hash_size": 59, "type": "unknown"},
    {"feature_name": "index_is_live_streamer", "is_ragged": False,
        "row": 86, "hash_size": 3, "type": "unknown"},
    {"feature_name": "index_user_id", "is_ragged": False,
        "row": 87, "hash_size": 27078, "type": "unknown"},
    {"feature_name": "index_video_id", "is_ragged": False,
        "row": 88, "hash_size": 7552, "type": "unknown"},
    {"feature_name": "index_author_id", "is_ragged": False,
        "row": 89, "hash_size": 6490, "type": "unknown"},
    {"feature_name": "index_music_id", "is_ragged": False,
        "row": 90, "hash_size": 7173, "type": "unknown"},
    {"feature_name": "is_video_author", "is_ragged": False,
        "row": 91, "hash_size": 3, "type": "unknown"},
    {"feature_name": "music_type", "is_ragged": False,
        "row": 92, "hash_size": 13, "type": "unknown"},
]


# +-----------------------------------------------------------------------------------------+
# |percentile_approx(play_time_s, array(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9), 10000)|
# +-----------------------------------------------------------------------------------------+
# |[1, 1, 2, 4, 7, 13, 23, 40, 77]                                                          |
# +-----------------------------------------------------------------------------------------+
# Max = 96

percentiles = [5, 10, 20, 30, 40, 50, 60, 70, 80, 90]


def preprocess_row(*row):
    features = {}
    for config in feature_config:
        if features.get(config["feature_name"]) is None:
            if config["is_ragged"]:
                features[config["feature_name"]] = tf.strings.to_number(
                    tf.strings.split(row[config["row"]], sep=';'), out_type=tf.int32)
            else:
                features[config["feature_name"]] = row[config["row"]]
    score = tf.cast(row[-1], dtype=tf.float32)
    return {
        "features": features,
        "labels": {
            f"label_{i}": tf.cast(row[-1] > percentiles[i], dtype=tf.float32) for i in range(len(percentiles))
        },
        "score": score
    }
